[tool.poetry]
name = "scrup-base"
version = "0.1.0"
description = ""
authors = ["Alex Pavlov <yukiu217@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
loguru = "^0.7.3"
selenium = {extras = ["py"], version = "^4.34.2"}
kafka-python = "^2.2.15"
selenium-wire = "^5.1.0"
pydantic-settings = "^2.10.1"
environs = "^14.2.0"


[tool.poetry.group.linters.dependencies]
mypy = "^1.17.0"
black = "^25.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
